### ISSUE TITLE
Suggestion: add an optional argument N that pastes the last N clipboard items

### ISSUE THREAD

**Issue by fabioperez** [vitorgalvao/sequential-paste-workflow#1]
### Feature details

Example: `paste 3` is the equivalent of calling `paste` three times.

**Comment by vitorgalvao** [comment]
Try [this version](https://github.com/user-attachments/files/17704108/Sequential.Paste.alfredworkflow.zip).

**Comment by vitorgalvao** [comment]
Try [this version](https://github.com/user-attachments/files/17704108/Sequential.Paste.alfredworkflow.zip). If all’s well, I’ll eventually release it.

**Comment by fabioperez** [comment]
@vitorgalvao sorry for the delay!


It didn't work for me. It was only pasting one item.

In any case, I'm using a snippet trigger for sequential paste: [paste_n.zip](https://github.com/user-attachments/files/18128060/paste_n.zip)
